---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
#    flux.weave.works/tag.sidecar: glob:3.*
  annotations:
    some.other.com/foo: bar
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.helloworld: regexp:^latest|alpine$
  name: helloworld
  namespace: hello
spec:
  minReadySeconds: 1
  replicas: 5
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      initContainers:
      - name: init
        image: quay.io/weaveworks/helloworld:master-07a1b6b
        args:
        - -msg=Init
      containers:
      - name: helloworld
        image: weaveworks/hello-world:alpine
        args:
        - -greeting=Ahoy
        ports:
        - containerPort: 80
      restartPolicy: Always
