---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: hello
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: hello
        image: quay.io/weaveworks/helloworld:master-07a1b6b
        ports:
        - containerPort: 80
      - name: ecrtest
        image: abc123.dkr.ecr.eu-west-1.amazonaws.com/burble/burble:v1
      restartPolicy: Always
