---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: hello
  annotations:
    flux.weave.works/automated: 'true'
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: mello
        image: quay.io/weaveworks/helloworld:master-07a1b6b
        ports:
        - containerPort: 80
      restartPolicy: Always
