---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: hello
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"I am locking this resource to test using version
      1.12 in weave cloud"'
    flux.weave.works/locked_user: Michael Bridgen <michael@weave.works>
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: fello
        image: quay.io/weaveworks/helloworld:master-07a1b6b
        ports:
        - containerPort: 80
      restartPolicy: Always
