---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: hello
spec:
  minReadySeconds: 5
  replicas: 5
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: hello
        image: quay.io/weaveworks/helloworld:master-07a1b6b
        ports:
        - containerPort: 80
      restartPolicy: Always
