---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
#    flux.weave.works/tag.sidecar: glob:3.*
  annotations:
    some.other.com/foo: bar
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.helloworld: glob:master-a00000*
  name: helloworld
  namespace: hello
spec:
  minReadySeconds: 1
  replicas: 5
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/weaveworks/helloworld:master-9a16ff945b9e
        args:
        - -msg=Bilbo Baggins
        ports:
        - containerPort: 80
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000002
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
      restartPolicy: Always
