---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: hello
  annotations:
    fluxcd.io/automated: 'true'
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: mello
        image: squaremo/helloworld:master-a000002
        ports:
        - containerPort: 80
      restartPolicy: Always
