apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: hello
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30088
  selector:
    name: helloworld
