---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxd
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxd
    spec:
      containers:
      - name: fluxd
        image: quay.io/weaveworks/fluxd
        imagePullPolicy: IfNotPresent
        args:
        - --token=pj38xti4qc3zaz1n4afyc675g3kzf88a
        #  connect to the local service
        - --fluxsvc-address=ws://frontend.default.svc.cluster.local/api/flux

