---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxd
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxd
    spec:
      serviceAccountName: weave-flux
      containers:
      - name: fluxd
        image: quay.io/weaveworks/fluxd
        imagePullPolicy: IfNotPresent
        args:
        - --token=dhne9qr8c9mez4nijaurdtrcb5uqjkwc
        #  connect to the local service
        - --fluxsvc-address=ws://authfe.default.svc.cluster.local/api/flux

