---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: garbage
  namespace: default
spec:
  chart:
    git: https://github.com/squaremo/flux-example
    path: charts/garbage
  values:
    unused: "force a re-release"
