---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: mariadb
  namespace: default
  labels:
    chart: mariadb
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chartGitPath: mariadb
  values:
    image: bitnami/mariadb:10.1.34-ol-7-r12
    persistence:
      enabled: false
