---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: default
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mariadb
    version: 4.4.2
  values:
    maria:
      image: bitnami/mariadb:10.1.37-ol-7-r46
    frank:
      image: sidecars-inc/frank
      tag: v1
      noise: here
    des:
      mondo: true
      image:
        repository: sidecars-inc/desmondo
        tag: 0.1.8
    persistence:
      enabled: false
