apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
spec:
  chart:
    repository: https://helm.iowa.weavedx.com
    name: podinfo-flagger
    version: 2.0.0
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 0.0.6
