---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: backend
spec:
  chart:
    git: git@github.com:squaremo/flux-helm-test
    path: charts/podinfo
  releaseName: backend
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 43df2d1
