apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: default
  labels:
    chart: podinfo
spec:
  chart:
    git: git@github.com:squaremo/flux-helm-test
    path: charts/podinfo
  releaseName: backend
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 0.0.9
